name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Check CSV_URL
        run: echo "CSV_URL is $CSV_URL"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run_id: $RUN_ID"
      
      - name: Build Docker Image from MLflow model
        run: |
          mlflow models build-docker --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/model" --name "cc"

      - name: Validate Docker Secrets
        run: |
          if [ -z "${{ secrets.USERNAME_DOCKER }}" ] || [ -z "${{ secrets.TOKEN_DOCKER }}" ]; then
            echo "🚨 Secrets not available. Please set USERNAME_DOCKER and TOKEN_DOCKER in repo settings."
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.TOKEN_DOCKER }}

      - name: Tag Docker image
        run: |
          docker tag cc ${{ secrets.USERNAME_DOCKER }}/cc:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.USERNAME_DOCKER }}/cc:latest
